[package]
name = "vbw-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vbw-proto = { path = "../vbw-proto" }
tonic.workspace = true
prost.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
clap = { version = "4", features = ["derive"] }
rustyline = { version = "14", default-features = false, features = ["with-file-history"] }
