[package]
name = "visp-llm"
version.workspace = true
edition.workspace = true

[dependencies]
visp-core = { path = "../visp-core" }
reqwest.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util = "0.7"
futures.workspace = true
async-trait.workspace = true
tracing.workspace = true
