[package]
name = "visp"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
chrono.workspace = true
serde.workspace = true
tokio.workspace = true
toml = "0.8"
tonic.workspace = true
visp-proto = { path = "../visp-proto" }
visp-config = { path = "../visp-config" }
visp-hooks = { path = "../visp-hooks" }

[dev-dependencies]
tempfile = "3"
